# Trainer settings
accelerator: gpu
strategy: auto
devices: 1
num_nodes: 1
precision: 32-true
logger: 
  class_path: pytorch_lightning.loggers.wandb.WandbLogger
  init_args:
    project: wildfire_progression
    log_model: true
callbacks: 
  - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
    init_args:
      monitor: val_loss
      mode: min
fast_dev_run: false
max_epochs: 500
check_val_every_n_epoch: 1
enable_progress_bar: true
default_root_dir: ./lightning_logs

# Model settings
model:
  class_path: models.SMPModel
  init_args:
    encoder_name: resnet34  # Specify a valid encoder name
    n_channels: 40
    flatten_temporal_dimension: true
    pos_class_weight: 2.0
    loss_function: BCE
    use_doy: false
    required_img_size: [128, 128]  # Optional based on your model requirements

# Datamodule settings
datamodule:
  class_path: dataloader.FireSpreadDataModule
  init_args:
    data_dir: /workspace/dataset/processed
    batch_size: 16
    n_leading_observations: 5
    n_leading_observations_test_adjustment: 0
    crop_side_length: 128
    load_from_hdf5: true
    num_workers: 4
    remove_duplicate_features: false
    features_to_keep: null
    return_doy: false
    data_fold_id: 0
